obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.290, 0.190], [0.290, -0.190], [-0.290, -0.190], [-0.290, 0.190]]
footprint: [[0.310, 0.210], [0.310, -0.210], [-0.310, -0.210], [-0.310, 0.210]]
#robot_radius: ir_of_robot
inflation_radius: 0.750

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}
